### ISSUE TITLE
Dependencies not installed when installing package?

### ISSUE THREAD

**Issue by pselle** [sarahgp/data-monster#6]
```
$ ./node_modules/data-monster/chomp.js viz.dm 

module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/pselle200/Sites/labweek/2015_06_datamonster/node_modules/data-monster/chomp.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Saw the same for rsvp, was fixed when I npm installed those

**Comment by sarahghp** [comment]
Lol, yeah apparently if you forget to save things in the `package.json`, they don't get installed.

**Comment by pselle** [comment]
:+1: :tada:
